name: tag

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: test
        run: |
          yarn install
          yarn test
