name: commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    defaults:
      run:
        shell: bash # needed for test command using pushd and popd

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: build
        run: |
          yarn install
          yarn eslint .
          yarn test