name: tag

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-20.04
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org
          always-auth: true

      - name: release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          yarn install
          yarn eslint .
          yarn test
          npm publish